// ===================================================================
// Action Group -- enterprise-grade-real-time
// Routes alert notifications to email and webhook endpoints
// Generated by: Enterprise DevEx Orchestrator Agent
// ===================================================================

@description('Project name for resource naming')
param projectName string

@description('Environment name')
param environment string

@description('Alert notification email address')
param alertEmail string

@description('Resource tags')
param tags object

resource actionGroup 'Microsoft.Insights/actionGroups@2023-01-01' = {
  name: 'ag-${projectName}-${environment}'
  location: 'global'
  tags: tags
  properties: {
    groupShortName: take(projectName, 12)
    enabled: true
    emailReceivers: [
      {
        name: 'OpsTeam'
        emailAddress: alertEmail
        useCommonAlertSchema: true
      }
    ]
    armRoleReceivers: [
      {
        name: 'MonitoringContributor'
        roleId: '43d0d8ad-25c7-4714-9337-8ba259a9fe05'
        useCommonAlertSchema: true
      }
    ]
  }
}

output actionGroupId string = actionGroup.id
output actionGroupName string = actionGroup.name
