// ===================================================================
// Azure Monitor Alert Rules -- enterprise-grade-real-time
// Generated by: Enterprise DevEx Orchestrator Agent
// ===================================================================

@description('Project name for resource naming')
param projectName string

@description('Environment name')
param environment string

@description('Container App resource ID for alert scoping')
param containerAppId string

@description('Key Vault resource ID for alert scoping')
param keyVaultId string

@description('Log Analytics workspace resource ID')
param logAnalyticsId string

@description('Action Group resource ID for alert routing')
param actionGroupId string

@description('Resource tags')
param tags object

// --- Container App Alerts --------------------------------------------

resource containerAppRestartAlert 'Microsoft.Insights/metricAlerts@2018-03-01' = {
  name: 'alert-${projectName}-restarts'
  location: 'global'
  tags: tags
  properties: {
    description: 'Container App restart count exceeds threshold'
    severity: 2
    enabled: true
    scopes: [
      containerAppId
    ]
    evaluationFrequency: 'PT5M'
    windowSize: 'PT15M'
    criteria: {
      'odata.type': 'Microsoft.Azure.Monitor.SingleResourceMultipleMetricCriteria'
      allOf: [
        {
          name: 'RestartCount'
          metricName: 'RestartCount'
          operator: 'GreaterThan'
          threshold: 3
          timeAggregation: 'Total'
          criterionType: 'StaticThresholdCriterion'
        }
      ]
    }
    actions: [
      {
        actionGroupId: actionGroupId
      }
    ]
  }
}

resource containerAppReplicaAlert 'Microsoft.Insights/metricAlerts@2018-03-01' = {
  name: 'alert-${projectName}-replicas'
  location: 'global'
  tags: tags
  properties: {
    description: 'Container App running replicas dropped to 0'
    severity: 1
    enabled: true
    scopes: [
      containerAppId
    ]
    evaluationFrequency: 'PT1M'
    windowSize: 'PT5M'
    criteria: {
      'odata.type': 'Microsoft.Azure.Monitor.SingleResourceMultipleMetricCriteria'
      allOf: [
        {
          name: 'RunningReplicas'
          metricName: 'Replicas'
          operator: 'LessThan'
          threshold: 1
          timeAggregation: 'Average'
          criterionType: 'StaticThresholdCriterion'
        }
      ]
    }
    actions: [
      {
        actionGroupId: actionGroupId
      }
    ]
  }
}

resource containerAppResponseTimeAlert 'Microsoft.Insights/metricAlerts@2018-03-01' = {
  name: 'alert-${projectName}-response-time'
  location: 'global'
  tags: tags
  properties: {
    description: 'Average response time exceeds 2 seconds'
    severity: 2
    enabled: true
    scopes: [
      containerAppId
    ]
    evaluationFrequency: 'PT5M'
    windowSize: 'PT15M'
    criteria: {
      'odata.type': 'Microsoft.Azure.Monitor.SingleResourceMultipleMetricCriteria'
      allOf: [
        {
          name: 'ResponseTime'
          metricName: 'Requests'
          operator: 'GreaterThan'
          threshold: 2000
          timeAggregation: 'Average'
          criterionType: 'StaticThresholdCriterion'
        }
      ]
    }
    actions: [
      {
        actionGroupId: actionGroupId
      }
    ]
  }
}

// --- Key Vault Alerts ------------------------------------------------

resource keyVaultAvailabilityAlert 'Microsoft.Insights/metricAlerts@2018-03-01' = {
  name: 'alert-${projectName}-kv-availability'
  location: 'global'
  tags: tags
  properties: {
    description: 'Key Vault availability dropped below 99%'
    severity: 1
    enabled: true
    scopes: [
      keyVaultId
    ]
    evaluationFrequency: 'PT5M'
    windowSize: 'PT15M'
    criteria: {
      'odata.type': 'Microsoft.Azure.Monitor.SingleResourceMultipleMetricCriteria'
      allOf: [
        {
          name: 'KVAvailability'
          metricName: 'Availability'
          operator: 'LessThan'
          threshold: 99
          timeAggregation: 'Average'
          criterionType: 'StaticThresholdCriterion'
        }
      ]
    }
    actions: [
      {
        actionGroupId: actionGroupId
      }
    ]
  }
}

resource keyVaultLatencyAlert 'Microsoft.Insights/metricAlerts@2018-03-01' = {
  name: 'alert-${projectName}-kv-latency'
  location: 'global'
  tags: tags
  properties: {
    description: 'Key Vault API latency exceeds 500ms'
    severity: 2
    enabled: true
    scopes: [
      keyVaultId
    ]
    evaluationFrequency: 'PT5M'
    windowSize: 'PT15M'
    criteria: {
      'odata.type': 'Microsoft.Azure.Monitor.SingleResourceMultipleMetricCriteria'
      allOf: [
        {
          name: 'KVLatency'
          metricName: 'ServiceApiLatency'
          operator: 'GreaterThan'
          threshold: 500
          timeAggregation: 'Average'
          criterionType: 'StaticThresholdCriterion'
        }
      ]
    }
    actions: [
      {
        actionGroupId: actionGroupId
      }
    ]
  }
}

// --- Log Analytics Scheduled Query Alert -----------------------------

resource errorRateAlert 'Microsoft.Insights/scheduledQueryRules@2023-03-15-preview' = {
  name: 'alert-${projectName}-error-rate'
  location: resourceGroup().location
  tags: tags
  properties: {
    description: 'Application error rate exceeds 5% in 15 minute window'
    severity: 2
    enabled: true
    scopes: [
      logAnalyticsId
    ]
    evaluationFrequency: 'PT5M'
    windowSize: 'PT15M'
    criteria: {
      allOf: [
        {
          query: 'ContainerAppConsoleLogs_CL | where Log_s contains "ERROR" or Log_s contains "CRITICAL" | summarize ErrorCount = count() by bin(TimeGenerated, 5m)'
          timeAggregation: 'Count'
          operator: 'GreaterThan'
          threshold: 10
          failingPeriods: {
            numberOfEvaluationPeriods: 3
            minFailingPeriodsToAlert: 2
          }
        }
      ]
    }
    actions: {
      actionGroups: [
        actionGroupId
      ]
    }
  }
}

resource slowQueryAlert 'Microsoft.Insights/scheduledQueryRules@2023-03-15-preview' = {
  name: 'alert-${projectName}-slow-queries'
  location: resourceGroup().location
  tags: tags
  properties: {
    description: 'Slow API queries exceeding 5s detected'
    severity: 3
    enabled: true
    scopes: [
      logAnalyticsId
    ]
    evaluationFrequency: 'PT5M'
    windowSize: 'PT15M'
    criteria: {
      allOf: [
        {
          query: 'ContainerAppConsoleLogs_CL | where Log_s contains "duration" | extend Duration = extract("duration[=:]\\s*(\\d+)", 1, Log_s) | where toint(Duration) > 5000 | summarize SlowCount = count() by bin(TimeGenerated, 5m)'
          timeAggregation: 'Count'
          operator: 'GreaterThan'
          threshold: 5
          failingPeriods: {
            numberOfEvaluationPeriods: 3
            minFailingPeriodsToAlert: 2
          }
        }
      ]
    }
    actions: {
      actionGroups: [
        actionGroupId
      ]
    }
  }
}

