"""Pytest configuration and shared fixtures.

Project: enterprise-grade-real-time
Generated by: Enterprise DevEx Orchestrator Agent
"""

from __future__ import annotations

import os
from unittest.mock import MagicMock, patch

import pytest
from fastapi.testclient import TestClient


@pytest.fixture(autouse=True)
def _env_setup(monkeypatch: pytest.MonkeyPatch) -> None:
    """Set required environment variables for all tests."""
    monkeypatch.setenv("KEY_VAULT_NAME", "kv-test-vault")
    monkeypatch.setenv("AZURE_CLIENT_ID", "00000000-0000-0000-0000-000000000000")
    monkeypatch.setenv("ENVIRONMENT", "test")
    monkeypatch.setenv("PORT", "8000")
    monkeypatch.setenv("STORAGE_ACCOUNT_URL", "https://testaccount.blob.core.windows.net")


@pytest.fixture
def mock_credential() -> MagicMock:
    """Mock DefaultAzureCredential."""
    with patch("src.app.main.DefaultAzureCredential") as mock:
        yield mock.return_value


@pytest.fixture
def mock_keyvault(mock_credential: MagicMock) -> MagicMock:
    """Mock SecretClient for Key Vault tests."""
    with patch("src.app.main.SecretClient") as mock:
        instance = mock.return_value
        instance.list_properties_of_secrets.return_value = []
        yield instance


@pytest.fixture
def client() -> TestClient:
    """Create FastAPI test client."""
    from src.app.main import app

    return TestClient(app)
