"""Enterprise DevEx Orchestrator -- Generated Application.

Project: intent-legal-contract-review
Description: # Intent: Legal Contract Review and Redlining AI

## Project Configuration

- **Project Name:** contract-review
- **App Type:** api
- **Data Stores:** blob, cosmos
- **Region:** eastus2
- **Environmen
Generated by: Enterprise DevEx Orchestrator Agent

This is a production-grade FastAPI application with:
- Health check endpoint
- Managed Identity authentication
- Key Vault integration
- Structured logging
"""

from __future__ import annotations

import logging
import os
from datetime import datetime, timezone

from azure.identity import DefaultAzureCredential
from azure.keyvault.secrets import SecretClient
from fastapi import FastAPI
from fastapi.responses import JSONResponse

from azure.storage.blob import BlobServiceClient

# -- Configuration ----------------------------------------------------
APP_NAME = "intent-legal-contract-review"
VERSION = "1.0.0"

# -- Logging ----------------------------------------------------------
logging.basicConfig(
    level=logging.INFO,
    format='{"timestamp":"%(asctime)s","level":"%(levelname)s","logger":"%(name)s","message":"%(message)s"}',
)
logger = logging.getLogger(APP_NAME)

# -- FastAPI Application ---------------------------------------------
app = FastAPI(
    title=APP_NAME,
    version=VERSION,
    description="# Intent: Legal Contract Review and Redlining AI

## Project Configuration

- **Project Name:** contract-review
- **App Type:** api
- **Data Stores:** blob, cosmos
- **Region:** eastus2
- **Environmen",
    docs_url="/docs",
    redoc_url=None,
)


# -- Key Vault Client ------------------------------------------------
def get_keyvault_client() -> SecretClient:
    """Create an authenticated Key Vault client using Managed Identity."""
    credential = DefaultAzureCredential(
        managed_identity_client_id=os.getenv("AZURE_CLIENT_ID")
    )
    vault_name = os.getenv("KEY_VAULT_NAME", "")
    if not vault_name:
        raise ValueError("KEY_VAULT_NAME environment variable not set")
    vault_url = f"https://{vault_name}.vault.azure.net"
    return SecretClient(vault_url=vault_url, credential=credential)


# -- Storage Client ---------------------------------------------------
def get_blob_client() -> BlobServiceClient:
    """Create an authenticated Blob Storage client using Managed Identity."""
    credential = DefaultAzureCredential(
        managed_identity_client_id=os.getenv("AZURE_CLIENT_ID")
    )
    account_url = os.getenv("STORAGE_ACCOUNT_URL", "")
    if not account_url:
        raise ValueError("STORAGE_ACCOUNT_URL environment variable not set")
    return BlobServiceClient(account_url=account_url, credential=credential)

# -- Health Endpoint --------------------------------------------------
@app.get("/health")
async def health():
    """Health check endpoint for liveness and readiness probes."""
    return {
        "status": "healthy",
        "service": APP_NAME,
        "version": VERSION,
        "timestamp": datetime.now(timezone.utc).isoformat(),
    }


# -- Info Endpoint ----------------------------------------------------
from fastapi.responses import JSONResponse, HTMLResponse
@app.get("/")
async def root():
    """Root endpoint with service information."""
    return {
        "service": APP_NAME,
        "version": VERSION,
        "status": "running",
        "docs": "/docs",
    }


# -- Key Vault Status ------------------------------------------------
@app.get("/keyvault/status")
async def keyvault_status():
async def root():
    """Root endpoint with HTML landing page."""
    html = f"""
    <!DOCTYPE html>
    <html>
    <head>
        <title>{APP_NAME}</title>
        <style>
            body {{ font-family: Arial, sans-serif; margin: 40px; background: #f5f5f5; }}
            .container {{ max-width: 600px; background: white; padding: 30px; border-radius: 8px; box-shadow: 0 2px 4px rgba(0,0,0,0.1); }}
            h1 {{ color: #0078d4; }}
            .status {{ color: #107c10; font-weight: bold; }}
            .links {{ margin-top: 20px; }}
            .links a {{ display: block; margin: 10px 0; padding: 10px; background: #0078d4; color: white; text-decoration: none; border-radius: 4px; text-align: center; }}
            .links a:hover {{ background: #106ebe; }}
        </style>
    </head>
    <body>
        <div class="container">
            <h1>{APP_NAME}</h1>
            <p><strong>Version:</strong> {VERSION}</p>
            <p><strong>Status:</strong> <span class="status">✓ Running</span></p>
            <div class="links">
                <a href="/docs">📚 API Documentation (Swagger UI)</a>
                <a href="/health">❤️ Health Check</a>
                <a href="/keyvault/status">🔐 Key Vault Status</a>
                <a href="/storage/status">📦 Storage Account Status</a>
            </div>
        </div>
    </body>
    </html>
    """
    return HTMLResponse(content=html)
        }
    except Exception as e:
        logger.error(f"Key Vault health check failed: {e}")
        return JSONResponse(
            status_code=503,
            content={"status": "error", "detail": str(e)},
        )



@app.get("/storage/status")
async def storage_status():
    """Check storage account connectivity."""
    try:
        client = get_blob_client()
        containers = list(client.list_containers(max_results=1))
        return {
            "status": "connected",
            "containers_accessible": True,
        }
    except Exception as e:
        logger.error(f"Storage health check failed: {e}")
        return JSONResponse(
            status_code=503,
            content={"status": "error", "detail": str(e)},
        )

# -- Startup Event ----------------------------------------------------
@app.on_event("startup")
async def startup():
    """Application startup tasks."""
    logger.info(f"{APP_NAME} v{VERSION} starting up")
    logger.info(f"Environment: {os.getenv('ENVIRONMENT', 'unknown')}")


@app.on_event("shutdown")
async def shutdown():
    """Application shutdown tasks."""
    logger.info(f"{APP_NAME} shutting down")


if __name__ == "__main__":
    import uvicorn
    port = int(os.getenv("PORT", "8000"))
    uvicorn.run(app, host="0.0.0.0", port=port)
