"""Enterprise DevEx Orchestrator -- Generated Application.

Project: enterprise-grade-real-time
Description: An enterprise-grade, real-time voice-to-voice agent system for Demo Health System (Demo) healthcare operations. Built with OpenAI's GPT-4o Realtime API for natural conversational experiences, backed b
Generated by: Enterprise DevEx Orchestrator Agent

This is a production-grade FastAPI application with:
- Health check endpoint
- Managed Identity authentication
- Key Vault integration
- Structured logging
"""

from __future__ import annotations

import logging
import os
from datetime import datetime, timezone

from azure.identity import DefaultAzureCredential
from azure.keyvault.secrets import SecretClient
from fastapi import FastAPI
from fastapi.responses import HTMLResponse, JSONResponse

from api.v1.router import router as v1_router

# -- Configuration ----------------------------------------------------
APP_NAME = "enterprise-grade-real-time"
VERSION = "1.0.0"

# -- Logging ----------------------------------------------------------
logging.basicConfig(
    level=logging.INFO,
    format='{"timestamp":"%(asctime)s","level":"%(levelname)s","logger":"%(name)s","message":"%(message)s"}',
)
logger = logging.getLogger(APP_NAME)

# -- FastAPI Application ---------------------------------------------
app = FastAPI(
    title=APP_NAME,
    version=VERSION,
    description="An enterprise-grade, real-time voice-to-voice agent system for Demo Health System (Demo) healthcare operations. Built with OpenAI's GPT-4o Realtime API for natural conversational experiences, backed b",
    docs_url="/docs",
    redoc_url=None,
)

# -- Mount versioned API router --------------------------------------
app.include_router(v1_router, prefix="/api/v1", tags=["v1"])


# -- Key Vault Client ------------------------------------------------
def get_keyvault_client() -> SecretClient:
    """Create an authenticated Key Vault client using Managed Identity.
    
    Supports two configuration patterns:
    1. KEY_VAULT_URI - full vault URL (https://vault-name.vault.azure.net)
    2. KEY_VAULT_NAME - vault name only (will construct URL)
    """
    credential = DefaultAzureCredential(
        managed_identity_client_id=os.getenv("AZURE_CLIENT_ID")
    )
    
    # Try full URI first (recommended)
    vault_uri = os.getenv("KEY_VAULT_URI", "")
    if vault_uri:
        return SecretClient(vault_url=vault_uri, credential=credential)
    
    # Fallback to name-based construction
    vault_name = os.getenv("KEY_VAULT_NAME", "")
    if not vault_name:
        raise ValueError("Either KEY_VAULT_URI or KEY_VAULT_NAME must be set")
    
    return SecretClient(
        vault_url=f"https://{vault_name}.vault.azure.net",
        credential=credential
    )


# -- Health Endpoint --------------------------------------------------
@app.get("/health")
async def health():
    """Health check endpoint for liveness and readiness probes."""
    return {
        "status": "healthy",
        "service": APP_NAME,
        "version": VERSION,
        "timestamp": datetime.now(timezone.utc).isoformat(),
    }


# -- Root Endpoint (HTML Landing Page) ------
@app.get("/")
async def root():
    """Root endpoint with basic HTML response."""
    html = f"""<!DOCTYPE html>
<html>
<head>
    <title>{APP_NAME}</title>
    <style>
        body {{ font-family: Arial, sans-serif; margin: 40px; background: #f5f5f5; }}
        .container {{ background: white; padding: 20px; border-radius: 8px; box-shadow: 0 2px 4px rgba(0,0,0,0.1); max-width: 600px; margin: 0 auto; }}
        h1 {{ color: #333; }}
        a {{ display: inline-block; margin-top: 10px; padding: 10px 15px; background: #0078d4; color: white; text-decoration: none; border-radius: 4px; }}
        a:hover {{ background: #106ebe; }}
    </style>
</head>
<body>
    <div class="container">
        <h1>{APP_NAME}</h1>
        <p>Version: {VERSION}</p>
        <p>Status: Running</p>
        <a href="/docs">📚 API Documentation</a>
        <a href="/health">💚 Health Check</a>
        <a href="/keyvault/status">🔐 Key Vault Status</a>
    </div>
</body>
</html>
"""
    return HTMLResponse(content=html)


# -- Key Vault Status ------------------------------------------------
@app.get("/keyvault/status")
async def keyvault_status():
    """Check Key Vault connectivity via Managed Identity."""
    try:
        client = get_keyvault_client()
        # List secrets to verify access (limited to 1)
        secrets = list(client.list_properties_of_secrets(max_page_size=1))
        return {
            "status": "connected",
            "vault_accessible": True,
        }
    except Exception as e:
        logger.error(f"Key Vault health check failed: {e}")
        return JSONResponse(
            status_code=503,
            content={"status": "error", "detail": str(e)},
        )


# -- Startup Event ----------------------------------------------------
@app.on_event("startup")
async def startup():
    """Application startup tasks."""
    logger.info(f"{APP_NAME} v{VERSION} starting up")
    logger.info(f"Environment: {os.getenv('ENVIRONMENT', 'unknown')}")


@app.on_event("shutdown")
async def shutdown():
    """Application shutdown tasks."""
    logger.info(f"{APP_NAME} shutting down")


if __name__ == "__main__":
    import uvicorn
    port = int(os.getenv("PORT", "8000"))
    uvicorn.run(app, host="0.0.0.0", port=port)
