"""Alert Generator -- produces Azure Monitor alert rules as Bicep.

Generates comprehensive monitoring alert rules including:
    - Container App health and performance alerts
    - Key Vault access and expiry alerts
    - Storage account availability alerts
    - Log Analytics workspace query alerts
    - Action group for alert routing
"""

from __future__ import annotations

from src.orchestrator.intent_schema import DataStore, IntentSpec
from src.orchestrator.logging import get_logger

logger = get_logger(__name__)


class AlertGenerator:
    """Generates Azure Monitor alert rules in Bicep."""

    def generate(self, spec: IntentSpec) -> dict[str, str]:
        """Generate alert rule Bicep files.

        Args:
            spec: The parsed intent specification.

        Returns:
            Mapping of file path -> content.
        """
        logger.info("alert_generator.start", project=spec.project_name)

        files: dict[str, str] = {}

        files["infra/modules/alerts.bicep"] = self._alerts_module(spec)
        files["infra/modules/action-group.bicep"] = self._action_group(spec)
        files["docs/alerting-runbook.md"] = self._alerting_runbook(spec)

        logger.info("alert_generator.complete", file_count=len(files))
        return files

    def _alerts_module(self, spec: IntentSpec) -> str:
        storage_alerts = ""
        if DataStore.BLOB_STORAGE in spec.data_stores:
            storage_alerts = """
// --- Storage Account Alerts ------------------------------------------
resource storageAvailabilityAlert 'Microsoft.Insights/metricAlerts@2018-03-01' = {
  name: 'alert-${projectName}-storage-availability'
  location: 'global'
  tags: tags
  properties: {
    description: 'Storage account availability dropped below 99.9%'
    severity: 1
    enabled: true
    scopes: [
      storageAccountId
    ]
    evaluationFrequency: 'PT5M'
    windowSize: 'PT15M'
    criteria: {
      'odata.type': 'Microsoft.Azure.Monitor.SingleResourceMultipleMetricCriteria'
      allOf: [
        {
          name: 'StorageAvailability'
          metricName: 'Availability'
          operator: 'LessThan'
          threshold: 99.9
          timeAggregation: 'Average'
          criterionType: 'StaticThresholdCriterion'
        }
      ]
    }
    actions: [
      {
        actionGroupId: actionGroupId
      }
    ]
  }
}

resource storageLatencyAlert 'Microsoft.Insights/metricAlerts@2018-03-01' = {
  name: 'alert-${projectName}-storage-latency'
  location: 'global'
  tags: tags
  properties: {
    description: 'Storage E2E latency exceeds 1000ms'
    severity: 2
    enabled: true
    scopes: [
      storageAccountId
    ]
    evaluationFrequency: 'PT5M'
    windowSize: 'PT15M'
    criteria: {
      'odata.type': 'Microsoft.Azure.Monitor.SingleResourceMultipleMetricCriteria'
      allOf: [
        {
          name: 'StorageLatency'
          metricName: 'SuccessE2ELatency'
          operator: 'GreaterThan'
          threshold: 1000
          timeAggregation: 'Average'
          criterionType: 'StaticThresholdCriterion'
        }
      ]
    }
    actions: [
      {
        actionGroupId: actionGroupId
      }
    ]
  }
}
"""

        storage_param = ""
        if DataStore.BLOB_STORAGE in spec.data_stores:
            storage_param = """
@description('Storage Account resource ID for alert scoping')
param storageAccountId string
"""

        return f"""// ===================================================================
// Azure Monitor Alert Rules -- {spec.project_name}
// Generated by: Enterprise DevEx Orchestrator Agent
// ===================================================================

@description('Project name for resource naming')
param projectName string

@description('Environment name')
param environment string

@description('Container App resource ID for alert scoping')
param containerAppId string

@description('Key Vault resource ID for alert scoping')
param keyVaultId string

@description('Log Analytics workspace resource ID')
param logAnalyticsId string

@description('Action Group resource ID for alert routing')
param actionGroupId string
{storage_param}
@description('Resource tags')
param tags object

// --- Container App Alerts --------------------------------------------

resource containerAppRestartAlert 'Microsoft.Insights/metricAlerts@2018-03-01' = {{
  name: 'alert-${{projectName}}-restarts'
  location: 'global'
  tags: tags
  properties: {{
    description: 'Container App restart count exceeds threshold'
    severity: 2
    enabled: true
    scopes: [
      containerAppId
    ]
    evaluationFrequency: 'PT5M'
    windowSize: 'PT15M'
    criteria: {{
      'odata.type': 'Microsoft.Azure.Monitor.SingleResourceMultipleMetricCriteria'
      allOf: [
        {{
          name: 'RestartCount'
          metricName: 'RestartCount'
          operator: 'GreaterThan'
          threshold: 3
          timeAggregation: 'Total'
          criterionType: 'StaticThresholdCriterion'
        }}
      ]
    }}
    actions: [
      {{
        actionGroupId: actionGroupId
      }}
    ]
  }}
}}

resource containerAppReplicaAlert 'Microsoft.Insights/metricAlerts@2018-03-01' = {{
  name: 'alert-${{projectName}}-replicas'
  location: 'global'
  tags: tags
  properties: {{
    description: 'Container App running replicas dropped to 0'
    severity: 1
    enabled: true
    scopes: [
      containerAppId
    ]
    evaluationFrequency: 'PT1M'
    windowSize: 'PT5M'
    criteria: {{
      'odata.type': 'Microsoft.Azure.Monitor.SingleResourceMultipleMetricCriteria'
      allOf: [
        {{
          name: 'RunningReplicas'
          metricName: 'Replicas'
          operator: 'LessThan'
          threshold: 1
          timeAggregation: 'Average'
          criterionType: 'StaticThresholdCriterion'
        }}
      ]
    }}
    actions: [
      {{
        actionGroupId: actionGroupId
      }}
    ]
  }}
}}

resource containerAppResponseTimeAlert 'Microsoft.Insights/metricAlerts@2018-03-01' = {{
  name: 'alert-${{projectName}}-response-time'
  location: 'global'
  tags: tags
  properties: {{
    description: 'Average response time exceeds 2 seconds'
    severity: 2
    enabled: true
    scopes: [
      containerAppId
    ]
    evaluationFrequency: 'PT5M'
    windowSize: 'PT15M'
    criteria: {{
      'odata.type': 'Microsoft.Azure.Monitor.SingleResourceMultipleMetricCriteria'
      allOf: [
        {{
          name: 'ResponseTime'
          metricName: 'Requests'
          operator: 'GreaterThan'
          threshold: 2000
          timeAggregation: 'Average'
          criterionType: 'StaticThresholdCriterion'
        }}
      ]
    }}
    actions: [
      {{
        actionGroupId: actionGroupId
      }}
    ]
  }}
}}

// --- Key Vault Alerts ------------------------------------------------

resource keyVaultAvailabilityAlert 'Microsoft.Insights/metricAlerts@2018-03-01' = {{
  name: 'alert-${{projectName}}-kv-availability'
  location: 'global'
  tags: tags
  properties: {{
    description: 'Key Vault availability dropped below 99%'
    severity: 1
    enabled: true
    scopes: [
      keyVaultId
    ]
    evaluationFrequency: 'PT5M'
    windowSize: 'PT15M'
    criteria: {{
      'odata.type': 'Microsoft.Azure.Monitor.SingleResourceMultipleMetricCriteria'
      allOf: [
        {{
          name: 'KVAvailability'
          metricName: 'Availability'
          operator: 'LessThan'
          threshold: 99
          timeAggregation: 'Average'
          criterionType: 'StaticThresholdCriterion'
        }}
      ]
    }}
    actions: [
      {{
        actionGroupId: actionGroupId
      }}
    ]
  }}
}}

resource keyVaultLatencyAlert 'Microsoft.Insights/metricAlerts@2018-03-01' = {{
  name: 'alert-${{projectName}}-kv-latency'
  location: 'global'
  tags: tags
  properties: {{
    description: 'Key Vault API latency exceeds 500ms'
    severity: 2
    enabled: true
    scopes: [
      keyVaultId
    ]
    evaluationFrequency: 'PT5M'
    windowSize: 'PT15M'
    criteria: {{
      'odata.type': 'Microsoft.Azure.Monitor.SingleResourceMultipleMetricCriteria'
      allOf: [
        {{
          name: 'KVLatency'
          metricName: 'ServiceApiLatency'
          operator: 'GreaterThan'
          threshold: 500
          timeAggregation: 'Average'
          criterionType: 'StaticThresholdCriterion'
        }}
      ]
    }}
    actions: [
      {{
        actionGroupId: actionGroupId
      }}
    ]
  }}
}}

// --- Log Analytics Scheduled Query Alert -----------------------------

resource errorRateAlert 'Microsoft.Insights/scheduledQueryRules@2023-03-15-preview' = {{
  name: 'alert-${{projectName}}-error-rate'
  location: resourceGroup().location
  tags: tags
  properties: {{
    description: 'Application error rate exceeds 5% in 15 minute window'
    severity: 2
    enabled: true
    scopes: [
      logAnalyticsId
    ]
    evaluationFrequency: 'PT5M'
    windowSize: 'PT15M'
    criteria: {{
      allOf: [
        {{
          query: 'ContainerAppConsoleLogs_CL | where Log_s contains "ERROR" or Log_s contains "CRITICAL" | summarize ErrorCount = count() by bin(TimeGenerated, 5m)'
          timeAggregation: 'Count'
          operator: 'GreaterThan'
          threshold: 10
          failingPeriods: {{
            numberOfEvaluationPeriods: 3
            minFailingPeriodsToAlert: 2
          }}
        }}
      ]
    }}
    actions: {{
      actionGroups: [
        actionGroupId
      ]
    }}
  }}
}}

resource slowQueryAlert 'Microsoft.Insights/scheduledQueryRules@2023-03-15-preview' = {{
  name: 'alert-${{projectName}}-slow-queries'
  location: resourceGroup().location
  tags: tags
  properties: {{
    description: 'Slow API queries exceeding 5s detected'
    severity: 3
    enabled: true
    scopes: [
      logAnalyticsId
    ]
    evaluationFrequency: 'PT5M'
    windowSize: 'PT15M'
    criteria: {{
      allOf: [
        {{
          query: 'ContainerAppConsoleLogs_CL | where Log_s contains "duration" | extend Duration = extract("duration[=:]\\\\s*(\\\\d+)", 1, Log_s) | where toint(Duration) > 5000 | summarize SlowCount = count() by bin(TimeGenerated, 5m)'
          timeAggregation: 'Count'
          operator: 'GreaterThan'
          threshold: 5
          failingPeriods: {{
            numberOfEvaluationPeriods: 3
            minFailingPeriodsToAlert: 2
          }}
        }}
      ]
    }}
    actions: {{
      actionGroups: [
        actionGroupId
      ]
    }}
  }}
}}
{storage_alerts}
"""

    def _action_group(self, spec: IntentSpec) -> str:
        return f"""// ===================================================================
// Action Group -- {spec.project_name}
// Routes alert notifications to email and webhook endpoints
// Generated by: Enterprise DevEx Orchestrator Agent
// ===================================================================

@description('Project name for resource naming')
param projectName string

@description('Environment name')
param environment string

@description('Alert notification email address')
param alertEmail string = 'ops-team@contoso.com'

@description('Resource tags')
param tags object

resource actionGroup 'Microsoft.Insights/actionGroups@2023-01-01' = {{
  name: 'ag-${{projectName}}-${{environment}}'
  location: 'global'
  tags: tags
  properties: {{
    groupShortName: take(projectName, 12)
    enabled: true
    emailReceivers: [
      {{
        name: 'OpsTeam'
        emailAddress: alertEmail
        useCommonAlertSchema: true
      }}
    ]
    armRoleReceivers: [
      {{
        name: 'MonitoringContributor'
        roleId: '43d0d8ad-25c7-4714-9337-8ba259a9fe05'
        useCommonAlertSchema: true
      }}
    ]
  }}
}}

output actionGroupId string = actionGroup.id
output actionGroupName string = actionGroup.name
"""

    def _alerting_runbook(self, spec: IntentSpec) -> str:
        storage_runbook = ""
        if DataStore.BLOB_STORAGE in spec.data_stores:
            storage_runbook = """
### Storage Availability Alert
- **Severity:** 1 (Critical)
- **Threshold:** Availability < 99.9%
- **Runbook:**
  1. Check Azure Status page for regional outages
  2. Verify storage account network rules
  3. Check storage account firewall settings
  4. Test connectivity from Container App subnet
  5. Escalate to Azure Support if regional issue

### Storage Latency Alert
- **Severity:** 2 (Warning)
- **Threshold:** E2E latency > 1000ms
- **Runbook:**
  1. Check blob sizes -- consider chunking large blobs
  2. Verify storage account is in same region as app
  3. Check concurrent connection counts
  4. Review storage account tier (Standard vs Premium)
"""

        return f"""# Alerting Runbook -- {spec.project_name}

> Generated by Enterprise DevEx Orchestrator Agent

## Alert Rules Summary

| Alert | Severity | Threshold | Window |
|-------|----------|-----------|--------|
| Container Restarts | 2 | > 3 restarts | 15 min |
| Zero Replicas | 1 | < 1 replica | 5 min |
| Response Time | 2 | > 2000ms avg | 15 min |
| Key Vault Availability | 1 | < 99% | 15 min |
| Key Vault Latency | 2 | > 500ms | 15 min |
| Error Rate | 2 | > 10 errors | 15 min |
| Slow Queries | 3 | > 5 slow reqs | 15 min |

## Runbooks

### Container App Restart Alert
- **Severity:** 2 (Warning)
- **Threshold:** > 3 restarts in 15 minutes
- **Runbook:**
  1. Check Container App logs: `az containerapp logs show`
  2. Look for OOMKilled events (memory limits)
  3. Check health probe configuration
  4. Verify container image is accessible from ACR
  5. Review recent deployments for breaking changes

### Zero Replicas Alert
- **Severity:** 1 (Critical)
- **Threshold:** Running replicas < 1
- **Runbook:**
  1. Check Container App status: `az containerapp show`
  2. Verify min replicas configuration (should be >= 1 for prod)
  3. Check Container Apps Environment health
  4. Review scaling rules and triggers
  5. Manually scale up: `az containerapp update --min-replicas 1`

### Response Time Alert
- **Severity:** 2 (Warning)
- **Threshold:** Average response > 2000ms
- **Runbook:**
  1. Check CPU and memory utilization
  2. Review active connections and request patterns
  3. Check downstream service latencies (Key Vault, Storage)
  4. Consider scaling up replicas or CPU/memory limits
  5. Enable distributed tracing for bottleneck analysis

### Key Vault Availability Alert
- **Severity:** 1 (Critical)
- **Threshold:** Availability < 99%
- **Runbook:**
  1. Check Azure Status page for Key Vault service issues
  2. Verify network rules allow Container App access
  3. Check Managed Identity permissions (Key Vault Secrets User)
  4. Test manual access: `az keyvault secret list --vault-name <name>`
  5. Verify Key Vault soft-delete and purge protection status

### Key Vault Latency Alert
- **Severity:** 2 (Warning)
- **Threshold:** API latency > 500ms
- **Runbook:**
  1. Check Key Vault throttling (429 responses)
  2. Implement client-side secret caching
  3. Reduce frequency of Key Vault calls
  4. Verify Key Vault is in same region as application
  5. Check concurrent request volume

### Error Rate Alert
- **Severity:** 2 (Warning)
- **Threshold:** > 10 errors in 15 minutes
- **Runbook:**
  1. Query Log Analytics for error details
  2. Correlate with recent deployments
  3. Check for dependency failures (external APIs, databases)
  4. Review application exception handling
  5. Check for resource exhaustion (connections, memory)

### Slow Queries Alert
- **Severity:** 3 (Informational)
- **Threshold:** > 5 requests exceeding 5 seconds
- **Runbook:**
  1. Identify slow endpoints from logs
  2. Enable request duration tracing
  3. Profile database queries if applicable
  4. Check for N+1 query patterns
  5. Consider adding caching layer
{storage_runbook}
## Action Group Configuration

- **Email:** ops-team@contoso.com
- **ARM Role:** Monitoring Contributor
- **Schema:** Common Alert Schema v2

## Escalation Matrix

| Severity | Response Time | Escalation |
|----------|---------------|------------|
| 0 (Critical) | 15 minutes | On-call + Management |
| 1 (Error) | 30 minutes | On-call engineer |
| 2 (Warning) | 2 hours | Engineering team |
| 3 (Info) | Next business day | Review in standup |
"""
