"""Application Generator — produces sample application code.

Generates a minimal but production-grade FastAPI application with:
    - Health endpoint
    - Managed Identity integration
    - Key Vault client
    - Storage client (if applicable)
    - Structured logging
    - Dockerfile
    - Requirements file
"""

from __future__ import annotations

from src.orchestrator.intent_schema import DataStore, IntentSpec
from src.orchestrator.logging import get_logger

logger = get_logger(__name__)


class AppGenerator:
    """Generates application scaffold."""

    def generate(self, spec: IntentSpec) -> dict[str, str]:
        """Generate application files."""
        logger.info("app_generator.start", project=spec.project_name)

        files: dict[str, str] = {}

        files["src/app/main.py"] = self._main_app(spec)
        files["src/app/requirements.txt"] = self._requirements(spec)
        files["src/app/Dockerfile"] = self._dockerfile(spec)
        files["src/app/__init__.py"] = '"""Generated application package."""\n'

        logger.info("app_generator.complete", file_count=len(files))
        return files

    def _main_app(self, spec: IntentSpec) -> str:
        storage_imports = ""
        storage_client = ""
        storage_endpoint = ""

        if DataStore.BLOB_STORAGE in spec.data_stores:
            storage_imports = """
from azure.storage.blob import BlobServiceClient
"""
            storage_client = """
# ── Storage Client ───────────────────────────────────────────────────
def get_blob_client() -> BlobServiceClient:
    \"\"\"Create an authenticated Blob Storage client using Managed Identity.\"\"\"
    credential = DefaultAzureCredential(
        managed_identity_client_id=os.getenv("AZURE_CLIENT_ID")
    )
    account_url = os.getenv("STORAGE_ACCOUNT_URL", "")
    if not account_url:
        raise ValueError("STORAGE_ACCOUNT_URL environment variable not set")
    return BlobServiceClient(account_url=account_url, credential=credential)
"""
            storage_endpoint = """

@app.get("/storage/status")
async def storage_status():
    \"\"\"Check storage account connectivity.\"\"\"
    try:
        client = get_blob_client()
        containers = list(client.list_containers(max_results=1))
        return {
            "status": "connected",
            "containers_accessible": True,
        }
    except Exception as e:
        logger.error(f"Storage health check failed: {e}")
        return JSONResponse(
            status_code=503,
            content={"status": "error", "detail": str(e)},
        )
"""

        return f"""\"\"\"Enterprise DevEx Orchestrator — Generated Application.

Project: {spec.project_name}
Description: {spec.description}
Generated by: Enterprise DevEx Orchestrator Agent

This is a production-grade FastAPI application with:
- Health check endpoint
- Managed Identity authentication
- Key Vault integration
- Structured logging
\"\"\"

from __future__ import annotations

import logging
import os
from datetime import datetime, timezone

from azure.identity import DefaultAzureCredential
from azure.keyvault.secrets import SecretClient
from fastapi import FastAPI
from fastapi.responses import JSONResponse
{storage_imports}
# ── Configuration ────────────────────────────────────────────────────
APP_NAME = "{spec.project_name}"
VERSION = "1.0.0"

# ── Logging ──────────────────────────────────────────────────────────
logging.basicConfig(
    level=logging.INFO,
    format='{{"timestamp":"%(asctime)s","level":"%(levelname)s","logger":"%(name)s","message":"%(message)s"}}',
)
logger = logging.getLogger(APP_NAME)

# ── FastAPI Application ─────────────────────────────────────────────
app = FastAPI(
    title=APP_NAME,
    version=VERSION,
    description="{spec.description}",
    docs_url="/docs",
    redoc_url=None,
)


# ── Key Vault Client ────────────────────────────────────────────────
def get_keyvault_client() -> SecretClient:
    \"\"\"Create an authenticated Key Vault client using Managed Identity.\"\"\"
    credential = DefaultAzureCredential(
        managed_identity_client_id=os.getenv("AZURE_CLIENT_ID")
    )
    vault_name = os.getenv("KEY_VAULT_NAME", "")
    if not vault_name:
        raise ValueError("KEY_VAULT_NAME environment variable not set")
    vault_url = f"https://{{vault_name}}.vault.azure.net"
    return SecretClient(vault_url=vault_url, credential=credential)

{storage_client}
# ── Health Endpoint ──────────────────────────────────────────────────
@app.get("/health")
async def health():
    \"\"\"Health check endpoint for liveness and readiness probes.\"\"\"
    return {{
        "status": "healthy",
        "service": APP_NAME,
        "version": VERSION,
        "timestamp": datetime.now(timezone.utc).isoformat(),
    }}


# ── Info Endpoint ────────────────────────────────────────────────────
@app.get("/")
async def root():
    \"\"\"Root endpoint with service information.\"\"\"
    return {{
        "service": APP_NAME,
        "version": VERSION,
        "status": "running",
        "docs": "/docs",
    }}


# ── Key Vault Status ────────────────────────────────────────────────
@app.get("/keyvault/status")
async def keyvault_status():
    \"\"\"Check Key Vault connectivity via Managed Identity.\"\"\"
    try:
        client = get_keyvault_client()
        # List secrets to verify access (limited to 1)
        secrets = list(client.list_properties_of_secrets(max_page_size=1))
        return {{
            "status": "connected",
            "vault_accessible": True,
        }}
    except Exception as e:
        logger.error(f"Key Vault health check failed: {{e}}")
        return JSONResponse(
            status_code=503,
            content={{"status": "error", "detail": str(e)}},
        )

{storage_endpoint}
# ── Startup Event ────────────────────────────────────────────────────
@app.on_event("startup")
async def startup():
    \"\"\"Application startup tasks.\"\"\"
    logger.info(f"{{APP_NAME}} v{{VERSION}} starting up")
    logger.info(f"Environment: {{os.getenv('ENVIRONMENT', 'unknown')}}")


@app.on_event("shutdown")
async def shutdown():
    \"\"\"Application shutdown tasks.\"\"\"
    logger.info(f"{{APP_NAME}} shutting down")


if __name__ == "__main__":
    import uvicorn
    port = int(os.getenv("PORT", "8000"))
    uvicorn.run(app, host="0.0.0.0", port=port)
"""

    def _requirements(self, spec: IntentSpec) -> str:
        reqs = """# Enterprise DevEx Orchestrator — Generated Application Dependencies
fastapi>=0.109.0
uvicorn[standard]>=0.27.0
azure-identity>=1.15.0
azure-keyvault-secrets>=4.8.0
pydantic>=2.5.0
python-dotenv>=1.0.0
"""
        if DataStore.BLOB_STORAGE in spec.data_stores:
            reqs += "azure-storage-blob>=12.19.0\n"
        if DataStore.COSMOS_DB in spec.data_stores:
            reqs += "azure-cosmos>=4.5.0\n"

        return reqs

    def _dockerfile(self, spec: IntentSpec) -> str:
        return f"""# ═══════════════════════════════════════════════════════════════════
# Dockerfile — {spec.project_name}
# Multi-stage build for minimal production image
# ═══════════════════════════════════════════════════════════════════

# ── Build Stage ──────────────────────────────────────────────────────
FROM python:3.11-slim AS builder

WORKDIR /build

COPY requirements.txt .
RUN pip install --no-cache-dir --prefix=/install -r requirements.txt

# ── Runtime Stage ────────────────────────────────────────────────────
FROM python:3.11-slim AS runtime

# Security: run as non-root user
RUN groupadd -r appuser && useradd -r -g appuser -d /app -s /sbin/nologin appuser

WORKDIR /app

# Copy installed packages from builder
COPY --from=builder /install /usr/local

# Copy application code
COPY . .

# Security: non-root user
USER appuser

# Expose port
EXPOSE 8000

# Health check
HEALTHCHECK --interval=30s --timeout=5s --start-period=10s --retries=3 \\
    CMD python -c "import urllib.request; urllib.request.urlopen('http://localhost:8000/health')"

# Start application
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000", "--workers", "2"]
"""
