// ===================================================================
// Enterprise DevEx Orchestrator -- Main Deployment
// Project: enterprise-grade-real-time
// Compute Target: container_apps
// Generated by: Enterprise DevEx Orchestrator Agent
// Naming Standard: Azure Cloud Adoption Framework (CAF)
// Tagging Standard: Enterprise governance policy
// ===================================================================

targetScope = 'resourceGroup'

// -- Parameters -----------------------------------------------------
@description('Project name used for resource naming')
@minLength(3)
@maxLength(39)
param projectName string

@description('Azure region for all resources')
param location string = resourceGroup().location

@description('Environment (dev, staging, prod)')
@allowed(['dev', 'staging', 'prod'])
param environment string = 'dev'

@description('Container image to deploy')
param containerImage string = 'mcr.microsoft.com/azuredocs/containerapps-helloworld:latest'

@description('Container app port')
param containerPort int = 8000

@description('Resource owner email for tagging')
param ownerEmail string = 'platform-team@contoso.com'

@description('Cost center for chargeback')
param costCenter string = 'DEFAULT-001'

// -- Variables ------------------------------------------------------
// -- Enterprise Naming Convention (Azure CAF) -------------------
// Resource names follow: {type}-{workload}-{env}-{region}
var lawName = 'law-${projectName}-${environment}-eus2'
var identityName = 'id-${projectName}-${environment}-eus2'
var kvName = take('kv-${projectName}-${environment}-eus2', 24)
var crName = replace('cr${projectName}${environment}eus2', '-', '')
var caeName = take('cae-${projectName}-${environment}-eus2', 32)
var caName = take('ca-${projectName}-${environment}-eus2', 32)
var stName = take(replace(toLower('st${projectName}${environment}eus2'), '-', ''), 24)

// -- Enterprise Tagging Standard ---------------------------------
// Required: project, environment, costCenter, owner, managedBy,
//           createdBy, dataSensitivity
// Optional: complianceScope, department, team, criticality, createdDate
var tags = {
  // Required tags (enterprise governance policy)
  project: projectName
  environment: environment
  costCenter: costCenter
  owner: ownerEmail
  managedBy: 'bicep'
  createdBy: 'enterprise-devex-orchestrator'
  dataSensitivity: 'confidential'
  // Optional tags (recommended)
  complianceScope: 'general'
  criticality: 'medium'
}

// -- Log Analytics (must deploy first for diagnostics) --------------
module logAnalytics 'modules/log-analytics.bicep' = {
  name: 'log-analytics-deployment'
  params: {
    location: location
    workspaceName: lawName
    tags: tags
  }
}

// -- Managed Identity -----------------------------------------------
module identity 'modules/managed-identity.bicep' = {
  name: 'identity-deployment'
  params: {
    location: location
    identityName: identityName
    tags: tags
  }
}

// -- Key Vault ------------------------------------------------------
module keyVault 'modules/keyvault.bicep' = {
  name: 'keyvault-deployment'
  params: {
    location: location
    keyVaultName: kvName
    managedIdentityPrincipalId: identity.outputs.principalId
    logAnalyticsWorkspaceId: logAnalytics.outputs.workspaceId
    tags: tags
  }
}

// -- Container Registry ---------------------------------------------
module containerRegistry 'modules/container-registry.bicep' = {
  name: 'acr-deployment'
  params: {
    location: location
    registryName: crName
    managedIdentityPrincipalId: identity.outputs.principalId
    logAnalyticsWorkspaceId: logAnalytics.outputs.workspaceId
    tags: tags
  }
}

// -- Cosmos DB ------------------------------------------------------
module cosmosDb 'modules/cosmos-db.bicep' = {
  name: 'cosmos-db-deployment'
  params: {
    location: location
    accountName: '${projectName}-cosmos'
    managedIdentityPrincipalId: identity.outputs.principalId
    logAnalyticsWorkspaceId: logAnalytics.outputs.workspaceId
    tags: tags
  }
}

// -- Redis Cache ----------------------------------------------------
module redis 'modules/redis.bicep' = {
  name: 'redis-deployment'
  params: {
    location: location
    redisName: '${projectName}-redis'
    managedIdentityPrincipalId: identity.outputs.principalId
    logAnalyticsWorkspaceId: logAnalytics.outputs.workspaceId
    tags: tags
  }
}

// -- Container App --------------------------------------------------
module containerApp 'modules/container-app.bicep' = {
  name: 'container-app-deployment'
  params: {
    location: location
    appName: caName
    environmentName: caeName
    containerImage: containerImage
    containerPort: containerPort
    managedIdentityId: identity.outputs.identityId
    managedIdentityClientId: identity.outputs.clientId
    logAnalyticsWorkspaceId: logAnalytics.outputs.workspaceId
    keyVaultName: keyVault.outputs.keyVaultName
    tags: tags
  }
}

// -- Outputs --------------------------------------------------------

output containerAppFqdn string = containerApp.outputs.fqdn
output containerAppName string = containerApp.outputs.appName
output containerRegistryName string = containerRegistry.outputs.registryName
output containerRegistryLoginServer string = containerRegistry.outputs.loginServer

output keyVaultName string = keyVault.outputs.keyVaultName
output logAnalyticsWorkspaceId string = logAnalytics.outputs.workspaceId
output managedIdentityClientId string = identity.outputs.clientId
output resourceGroupName string = resourceGroup().name
