"""Enterprise DevEx Orchestrator -- Generated Application.

Project: agent365
Description: Validation environment for MCP server exposed via APIM with EntraID RBAC for Copilot Studio.
Generated by: Enterprise DevEx Orchestrator Agent

This is a production-grade FastAPI application with:
- Health check endpoint
- Managed Identity authentication
- Key Vault integration
- Structured logging
"""

from __future__ import annotations

import logging
import os
from datetime import datetime, timezone

from azure.identity import DefaultAzureCredential
from azure.keyvault.secrets import SecretClient
from fastapi import FastAPI
from fastapi.responses import HTMLResponse, JSONResponse

from azure.storage.blob import BlobServiceClient

from api.v1.router import router as v1_router

# -- Configuration ----------------------------------------------------
APP_NAME = "agent365"
VERSION = "1.0.0"

# -- Logging ----------------------------------------------------------
logging.basicConfig(
    level=logging.INFO,
    format='{"timestamp":"%(asctime)s","level":"%(levelname)s","logger":"%(name)s","message":"%(message)s"}',
)
logger = logging.getLogger(APP_NAME)

# -- FastAPI Application ---------------------------------------------
app = FastAPI(
    title=APP_NAME,
    version=VERSION,
    description="Validation environment for MCP server exposed via APIM with EntraID RBAC for Copilot Studio.",
    docs_url="/docs",
    redoc_url=None,
)

# -- Mount versioned API router --------------------------------------
app.include_router(v1_router, prefix="/api/v1", tags=["v1"])


# -- Key Vault Client ------------------------------------------------
def get_keyvault_client() -> SecretClient:
    """Create an authenticated Key Vault client using Managed Identity.
    
    Supports two configuration patterns:
    1. KEY_VAULT_URI - full vault URL (https://vault-name.vault.azure.net)
    2. KEY_VAULT_NAME - vault name only (will construct URL)
    """
    credential = DefaultAzureCredential(
        managed_identity_client_id=os.getenv("AZURE_CLIENT_ID")
    )
    
    # Try full URI first (recommended)
    vault_uri = os.getenv("KEY_VAULT_URI", "")
    if vault_uri:
        return SecretClient(vault_url=vault_uri, credential=credential)
    
    # Fallback to name-based construction
    vault_name = os.getenv("KEY_VAULT_NAME", "")
    if not vault_name:
        raise ValueError("Either KEY_VAULT_URI or KEY_VAULT_NAME must be set")
    
    return SecretClient(
        vault_url=f"https://{vault_name}.vault.azure.net",
        credential=credential
    )


# -- Storage Client ---------------------------------------------------
def get_blob_client() -> BlobServiceClient:
    """Create an authenticated Blob Storage client using Managed Identity."""
    credential = DefaultAzureCredential(
        managed_identity_client_id=os.getenv("AZURE_CLIENT_ID")
    )
    account_url = os.getenv("STORAGE_ACCOUNT_URL", "")
    if not account_url:
        raise ValueError("STORAGE_ACCOUNT_URL environment variable not set")
    return BlobServiceClient(account_url=account_url, credential=credential)

# -- Health Endpoint --------------------------------------------------
@app.get("/health")
async def health():
    """Health check endpoint for liveness and readiness probes."""
    return {
        "status": "healthy",
        "service": APP_NAME,
        "version": VERSION,
        "timestamp": datetime.now(timezone.utc).isoformat(),
    }


# -- Root Endpoint (Enterprise Dashboard) ------
@app.get("/")
async def root():
    """Root endpoint -- enterprise dashboard."""
    compliance_badges = "<span class="compliance-badge general">Enterprise</span>
                    <span class="compliance-badge rbac">RBAC</span>"
    data_stores = "Blob Storage + Redis + Cosmos Db"
    html = f"""<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{APP_NAME} — Enterprise Dashboard</title>
    <style>
        :root {
            --primary: #0078d4;
            --primary-dark: #005a9e;
            --success: #107c10;
            --warning: #ff8c00;
            --danger: #d13438;
            --bg: #f3f2f1;
            --surface: #ffffff;
            --surface-alt: #faf9f8;
            --text: #323130;
            --text-secondary: #605e5c;
            --border: #edebe9;
            --shadow: 0 2px 8px rgba(0,0,0,.08);
            --shadow-lg: 0 8px 32px rgba(0,0,0,.12);
            --radius: 8px;
            --radius-lg: 12px;
        }
        * { margin: 0; padding: 0; box-sizing: border-box; }
        body { font-family: 'Segoe UI', -apple-system, BlinkMacSystemFont, sans-serif; background: var(--bg); color: var(--text); min-height: 100vh; }
        .topbar { background: linear-gradient(135deg, #0078d4 0%, #005a9e 100%); color: white; padding: 0 32px; height: 48px; display: flex; align-items: center; justify-content: space-between; font-size: 13px; box-shadow: 0 1px 4px rgba(0,0,0,.15); position: sticky; top: 0; z-index: 100; }
        .topbar-brand { display: flex; align-items: center; gap: 10px; font-weight: 600; font-size: 14px; }
        .topbar-brand svg { width: 20px; height: 20px; fill: white; }
        .topbar-meta { display: flex; gap: 20px; align-items: center; }
        .topbar-meta span { opacity: .85; }
        .env-badge { background: rgba(255,255,255,.2); padding: 2px 10px; border-radius: 12px; font-size: 11px; text-transform: uppercase; font-weight: 600; letter-spacing: .5px; }
        .hero { background: linear-gradient(180deg, #005a9e 0%, #0078d4 50%, var(--bg) 100%); padding: 48px 32px 64px; text-align: center; color: white; }
        .hero h1 { font-size: 28px; font-weight: 600; margin-bottom: 8px; }
        .hero p { font-size: 15px; opacity: .9; max-width: 640px; margin: 0 auto; line-height: 1.5; }
        .version-pill { display: inline-block; margin-top: 12px; background: rgba(255,255,255,.15); backdrop-filter: blur(8px); padding: 4px 16px; border-radius: 20px; font-size: 12px; font-weight: 500; }
        .dashboard { max-width: 1120px; margin: -40px auto 40px; padding: 0 24px; display: grid; grid-template-columns: repeat(auto-fit, minmax(320px, 1fr)); gap: 20px; }
        .card { background: var(--surface); border: 1px solid var(--border); border-radius: var(--radius-lg); box-shadow: var(--shadow); overflow: hidden; transition: box-shadow .2s, transform .15s; }
        .card:hover { box-shadow: var(--shadow-lg); transform: translateY(-2px); }
        .card-header { padding: 16px 20px 12px; display: flex; align-items: center; gap: 10px; border-bottom: 1px solid var(--border); background: var(--surface-alt); }
        .card-header h3 { font-size: 14px; font-weight: 600; color: var(--text); }
        .card-icon { width: 32px; height: 32px; border-radius: 8px; display: flex; align-items: center; justify-content: center; font-size: 16px; flex-shrink: 0; }
        .card-body { padding: 20px; }
        .status-grid { display: grid; grid-template-columns: 1fr 1fr; gap: 16px; }
        .status-item { text-align: center; }
        .status-item .label { font-size: 11px; text-transform: uppercase; letter-spacing: .8px; color: var(--text-secondary); margin-bottom: 4px; }
        .status-item .value { font-size: 20px; font-weight: 700; }
        .status-item .value.ok { color: var(--success); }
        .status-item .value.warn { color: var(--warning); }
        .status-dot { display: inline-block; width: 8px; height: 8px; border-radius: 50%; margin-right: 4px; animation: pulse 2s ease-in-out infinite; }
        .status-dot.green { background: var(--success); }
        @keyframes pulse { 0%, 100% { opacity: 1; } 50% { opacity: .4; } }
        .endpoint-list { list-style: none; }
        .endpoint-list li { display: flex; align-items: center; padding: 10px 0; border-bottom: 1px solid var(--border); gap: 12px; }
        .endpoint-list li:last-child { border-bottom: none; }
        .method-badge { font-size: 10px; font-weight: 700; padding: 2px 8px; border-radius: 4px; font-family: 'Consolas', 'Courier New', monospace; letter-spacing: .5px; min-width: 40px; text-align: center; }
        .method-badge.get { background: #e6f4ea; color: var(--success); }
        .method-badge.post { background: #e3f2fd; color: var(--primary); }
        .endpoint-path { font-family: 'Consolas', 'Courier New', monospace; font-size: 13px; color: var(--text); font-weight: 500; }
        .endpoint-desc { font-size: 12px; color: var(--text-secondary); margin-left: auto; }
        .actions { display: flex; flex-direction: column; gap: 10px; }
        .action-btn { display: flex; align-items: center; gap: 10px; padding: 12px 16px; border: 1px solid var(--border); border-radius: var(--radius); background: var(--surface); color: var(--text); text-decoration: none; font-size: 13px; font-weight: 500; transition: all .15s; }
        .action-btn:hover { background: var(--primary); color: white; border-color: var(--primary); }
        .action-btn .icon { font-size: 18px; width: 24px; text-align: center; }
        .arch-list { list-style: none; }
        .arch-list li { display: flex; align-items: center; gap: 10px; padding: 8px 0; font-size: 13px; border-bottom: 1px solid var(--border); }
        .arch-list li:last-child { border-bottom: none; }
        .arch-badge { font-size: 10px; font-weight: 600; padding: 3px 8px; border-radius: 4px; text-transform: uppercase; letter-spacing: .3px; }
        .arch-badge.compute { background: #e3f2fd; color: #1565c0; }
        .arch-badge.data { background: #e8f5e9; color: #2e7d32; }
        .arch-badge.security { background: #fce4ec; color: #c62828; }
        .arch-badge.monitor { background: #fff3e0; color: #e65100; }
        .compliance-row { display: flex; flex-wrap: wrap; gap: 8px; margin-top: 12px; }
        .compliance-badge { font-size: 11px; font-weight: 600; padding: 4px 12px; border-radius: 20px; border: 1px solid; }
        .compliance-badge.hipaa { background: #fce4ec; border-color: #ef9a9a; color: #b71c1c; }
        .compliance-badge.soc2 { background: #e8eaf6; border-color: #9fa8da; color: #283593; }
        .compliance-badge.rbac { background: #e0f2f1; border-color: #80cbc4; color: #00695c; }
        .compliance-badge.pci { background: #fff8e1; border-color: #ffe082; color: #f57f17; }
        .compliance-badge.fedramp { background: #e8eaf6; border-color: #7986cb; color: #1a237e; }
        .compliance-badge.iso { background: #f3e5f5; border-color: #ce93d8; color: #6a1b9a; }
        .compliance-badge.general { background: #eceff1; border-color: #b0bec5; color: #37474f; }
        .footer { text-align: center; padding: 24px; font-size: 12px; color: var(--text-secondary); border-top: 1px solid var(--border); max-width: 1120px; margin: 0 auto; }
        .footer a { color: var(--primary); text-decoration: none; }
        #health-status, #kv-status { transition: all .3s; }
    </style>
</head>
<body>
    <nav class="topbar">
        <div class="topbar-brand">
            <svg viewBox="0 0 24 24"><path d="M12 2L2 7l10 5 10-5-10-5zM2 17l10 5 10-5M2 12l10 5 10-5"/></svg>
            {APP_NAME}
        </div>
        <div class="topbar-meta">
            <span class="env-badge">dev</span>
            <span>eastus2</span>
        </div>
    </nav>
    <section class="hero">
        <h1>{APP_NAME}</h1>
        <p>Validation environment for MCP server exposed via APIM with EntraID RBAC for Copilot Studio.</p>
        <div class="version-pill">v{VERSION} · Container Apps</div>
    </section>
    <div class="dashboard">
        <div class="card">
            <div class="card-header"><div class="card-icon" style="background:#e6f4ea">💚</div><h3>System Status</h3></div>
            <div class="card-body">
                <div class="status-grid">
                    <div class="status-item"><div class="label">Health</div><div id="health-status" class="value">Checking…</div></div>
                    <div class="status-item"><div class="label">Key Vault</div><div id="kv-status" class="value">Checking…</div></div>
                    <div class="status-item"><div class="label">Region</div><div class="value" style="font-size:14px">eastus2</div></div>
                    <div class="status-item"><div class="label">Environment</div><div class="value" style="font-size:14px;text-transform:capitalize">dev</div></div>
                </div>
            </div>
        </div>
        <div class="card">
            <div class="card-header"><div class="card-icon" style="background:#e3f2fd">⚡</div><h3>Quick Actions</h3></div>
            <div class="card-body">
                <div class="actions">
                    <a class="action-btn" href="/docs"><span class="icon">📚</span>API Documentation</a>
                    <a class="action-btn" href="/health"><span class="icon">💚</span>Health Check</a>
                    <a class="action-btn" href="/keyvault/status"><span class="icon">🔐</span>Key Vault Status</a>
                    <a class="action-btn" href="/api/v1/items"><span class="icon">📦</span>API v1 Items</a>
                </div>
            </div>
        </div>
        <div class="card">
            <div class="card-header"><div class="card-icon" style="background:#fff3e0">🔌</div><h3>API Endpoints</h3></div>
            <div class="card-body">
                <ul class="endpoint-list">
                    <li><span class="method-badge get">GET</span><span class="endpoint-path">/health</span><span class="endpoint-desc">Liveness probe</span></li>
                    <li><span class="method-badge get">GET</span><span class="endpoint-path">/docs</span><span class="endpoint-desc">OpenAPI docs</span></li>
                    <li><span class="method-badge get">GET</span><span class="endpoint-path">/keyvault/status</span><span class="endpoint-desc">Vault connectivity</span></li>
                    <li><span class="method-badge get">GET</span><span class="endpoint-path">/api/v1/items</span><span class="endpoint-desc">Resource listing</span></li>
                    <li><span class="method-badge post">POST</span><span class="endpoint-path">/api/v1/items</span><span class="endpoint-desc">Create resource</span></li>
                </ul>
            </div>
        </div>
        <div class="card">
            <div class="card-header"><div class="card-icon" style="background:#fce4ec">🏗️</div><h3>Architecture &amp; Compliance</h3></div>
            <div class="card-body">
                <ul class="arch-list">
                    <li><span class="arch-badge compute">COMPUTE</span>Container Apps</li>
                    <li><span class="arch-badge data">DATA</span>{data_stores}</li>
                    <li><span class="arch-badge security">SECURITY</span>Managed Identity</li>
                    <li><span class="arch-badge monitor">MONITOR</span>Log Analytics · Health Probes</li>
                </ul>
                <div class="compliance-row">{compliance_badges}</div>
            </div>
        </div>
    </div>
    <footer class="footer">{APP_NAME} v{VERSION} · <a href="/docs">API Docs</a> · Enterprise DevEx Orchestrator</footer>
    <script>
        async function checkHealth() {
            try {
                const r = await fetch('/health');
                const d = await r.json();
                const el = document.getElementById('health-status');
                if (d.status === 'healthy') {
                    el.innerHTML = '<span class="status-dot green"></span>Healthy';
                    el.className = 'value ok';
                } else {
                    el.textContent = 'Degraded';
                    el.className = 'value warn';
                }
            } catch (e) {
                const el = document.getElementById('health-status');
                el.textContent = 'Unreachable';
                el.style.color = 'var(--danger)';
            }
        }
        async function checkKeyVault() {
            try {
                const r = await fetch('/keyvault/status');
                const d = await r.json();
                const el = document.getElementById('kv-status');
                if (d.status === 'connected') {
                    el.innerHTML = '<span class="status-dot green"></span>Connected';
                    el.className = 'value ok';
                } else {
                    el.textContent = 'Not configured';
                    el.style.color = 'var(--warning)';
                    el.style.fontSize = '14px';
                }
            } catch (e) {
                const el = document.getElementById('kv-status');
                el.textContent = 'Not configured';
                el.style.color = 'var(--text-secondary)';
                el.style.fontSize = '14px';
            }
        }
        checkHealth();
        checkKeyVault();
        setInterval(checkHealth, 30000);
    </script>
</body>
</html>
"""
    return HTMLResponse(content=html)


# -- Key Vault Status ------------------------------------------------
@app.get("/keyvault/status")
async def keyvault_status():
    """Check Key Vault connectivity via Managed Identity."""
    try:
        client = get_keyvault_client()
        # List secrets to verify access (limited to 1)
        secrets = list(client.list_properties_of_secrets(max_page_size=1))
        return {
            "status": "connected",
            "vault_accessible": True,
        }
    except Exception as e:
        logger.error(f"Key Vault health check failed: {e}")
        return JSONResponse(
            status_code=503,
            content={"status": "error", "detail": str(e)},
        )



@app.get("/storage/status")
async def storage_status():
    """Check storage account connectivity."""
    try:
        client = get_blob_client()
        containers = list(client.list_containers(max_results=1))
        return {
            "status": "connected",
            "containers_accessible": True,
        }
    except Exception as e:
        logger.error(f"Storage health check failed: {e}")
        return JSONResponse(
            status_code=503,
            content={"status": "error", "detail": str(e)},
        )

# -- Startup Event ----------------------------------------------------
@app.on_event("startup")
async def startup():
    """Application startup tasks."""
    logger.info(f"{APP_NAME} v{VERSION} starting up")
    logger.info(f"Environment: {os.getenv('ENVIRONMENT', 'unknown')}")


@app.on_event("shutdown")
async def shutdown():
    """Application shutdown tasks."""
    logger.info(f"{APP_NAME} shutting down")


if __name__ == "__main__":
    import uvicorn
    port = int(os.getenv("PORT", "8000"))
    uvicorn.run(app, host="0.0.0.0", port=port)
